p1a p1b p2 p3: p1.cpp p1b.cpp problem2_revised.cpp kmeans_conditional_variable.cpp 
	g++ -lrt -fopenmp -o p1a p1.cpp 
	g++ -lrt -fopenmp -o p1b p1b.cpp  
	g++ -lrt -fopenmp -o p2 problem2_revised.cpp 
	g++ -lrt -fopenmp -o p3 kmeans_conditional_variable.cpp -std=c++11